### ISSUE TITLE
Handle unavailability of the RTM website gracefully

### ISSUE THREAD

**Issue by threepistons** [threepistons/rtm-lcd-status#12]
**Given** Debian 10.3 with Python 3.7.3 and all dependencies installed.

**When I** ran ```./rtmstatus.py``` and left it running for a long time.

**In order to** display my count of pending and overdue tasks.

**Then** I get after some time
```
nuc@nuc:~/git/rtm-lcd-status$ ./rtmstatus.py 
Press Ctrl+C to quit
Traceback (most recent call last):
  File "./rtmstatus.py", line 111, in <module>
    workhorse()
  File "./rtmstatus.py", line 89, in workhorse
    count[section] = taskcounter(config.get(section, 'filter'), api)
  File "./rtmstatus.py", line 16, in taskcounter
    result = api.rtm.tasks.getList(filter=myfilter)
  File "/home/nuc/.local/lib/python3.7/site-packages/rtmapi/__init__.py", line 143, in __call__
    return self.rtm._call_method_auth(self.name, **params)
  File "/home/nuc/.local/lib/python3.7/site-packages/rtmapi/__init__.py", line 112, in _call_method_auth
    return self._call_method(method_name, **all_params)
  File "/home/nuc/.local/lib/python3.7/site-packages/rtmapi/__init__.py", line 106, in _call_method
    method_name, err.get("code"), err.get("msg"))
rtmapi.RtmRequestFailedException: Request rtm.tasks.getList failed. Status: 105, reason: Service currently unavailable.

```
and the LCD backlight stayed on with the text still displayed on the LCD screen, but did not update as I altered my tasks.  When I restarted rtmstatus.py, the LCD started updating again.

**I expected** the script to continue to run without filling the screen with error messages.

**Comment by threepistons** [comment]
Fixed by ab61483
